const mainNavigationRoutes = {
  home: "Home",
  tab_home: "TabHome",
  login: "LogIn",
  forgotPasscode: "ForgotPassCode",
  noInternetScreen: "NoInternetScreen",
  accountDetails: "AccountDetails",
  loanAccountDetails: "loanAccountDetails",
  RDAccountDetails: "RDAccountDetails",
  findAccount: "FindAccount",
  findLoanAccount: "FindLoanAccount",
  findRDAccount: "FindRDAccount",
  accountPreview: "AccountPreview",
  loanAccountPreview: "loanAccountPreview",
  RDAccountPreview: "RDAccountPreview",
  settingScreen: "SettingScreen",
  profileScreen: "profileScreen",
  endWorkScreen: "EndWorkScreen",
  changePinScreen: "ChangePinScreen",
  reportDayScreen: "ReportDayScreen",
  reportTypeScreen: "ReportTypeScreen",
  reportNoScreen: "ReportNoScreen",
  nonCollectionReport: "NonCollectionReport",
  miniStatement: "MiniStatement",
  miniStatementInner: "MiniStatementInner",
  dateWiseCollSummary: "DateWiseCollSummary",
  reportChooseScreen: "ReportChooseScreen",
  printerConnectScreen: "PrinterConnectScreen",
  duplicateReceipt: "DuplicateReceipt",
  duplicateReceiptInner: "DuplicateReceiptInnner",
  notificationScreen: "NotificationScreen",
  aboutScreen: "AboutScreen",
  lastFiveTnxScreen: "LastFiveTnxScreen",
  dayTotalReportScreen: "DayTotalReportScreen",
}

export default mainNavigationRoutes
